name: MenuPlus
main: MenuPlus\MenuPlus
version: 2.6.13
api:
 - 1.0.0
 - 2.0.0
 - 3.0.0
 - 3.0.0-ALPHA1
 - 3.0.0-ALPHA2
 - 3.0.0-ALPHA3
 - 3.0.0-ALPHA4
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 3.0.1
 - 3.0.2
 - 3.0.3 
 - 3.0.4
 - 3.1.0
 - 4.0.0
 - 5.0.0
 - 6.0.0
 - 7.0.0
 - 8.0.0
 - 9.0.0
load: POSTWORLD
author: Matt
softdepend: ["ZXDAKernel"]
description: A magical Menu Plugin

permissions:
 MenuPlus.*:
  default: true
  description: Allows to control all of functions in MenuPlus
  children:
   MenuPlus.command.*:
    default: true
    description: Allows to use all of commands in MenuPlus
    children:
     MenuPlus.command.menu:
      default: true
      description: